"use client"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { WordLearningTest } from "@/components/tests"

// Word data structure
interface Word {
  withGaps: string
  correct: string
}

export default function WordLearningPage() {
  // Sample words data
  const words: Word[] = [
    { "withGaps": "аукц..он", "correct": "аукцИон" },
    { "withGaps": "б..гаж", "correct": "бАгаж" },
    { "withGaps": "б..гровый", "correct": "бАгровый" },
    { "withGaps": "б..гряный", "correct": "бАгряный" },
    { "withGaps": "б..дм..нтон", "correct": "бАдмИнтон" },
    { "withGaps": "б..л..нсировать", "correct": "бАлАнсировать" },
    { "withGaps": "б..лкон", "correct": "бАлкон" },
    { "withGaps": "б..р..льеф", "correct": "бАрЕльеф" },
    { "withGaps": "б..ск..тбол", "correct": "бАскЕтбол" },
    { "withGaps": "б..ссейн", "correct": "бАссейн" },
    { "withGaps": "б..рёза", "correct": "бЕрёза" },
    { "withGaps": "б..речь", "correct": "бЕречь" },
    { "withGaps": "б..рюзовый", "correct": "бИрюзовый" },
    { "withGaps": "б..гатый", "correct": "бОгатый" },
    { "withGaps": "б..гатырь", "correct": "бОгатырь" },
    { "withGaps": "бр..ш..ра", "correct": "брОшЮра" },
    { "withGaps": "б..лл..тень", "correct": "бЮллЕтень" },
    { "withGaps": "в..кцина", "correct": "вАкцина" },
    { "withGaps": "в..р..ант", "correct": "вАрИант" },
    { "withGaps": "в..л..с..пед", "correct": "вЕлОсИпед" },
    { "withGaps": "в..нт..лятор", "correct": "вЕнтИлятор" },
    { "withGaps": "в..рм..шель", "correct": "вЕрмИшель" },
    { "withGaps": "в..ст..бюль", "correct": "вЕстИбюль" },
    { "withGaps": "в..т..ран", "correct": "вЕтЕран" },
    { "withGaps": "в..н..грет", "correct": "вИнЕгрет" },
    { "withGaps": "в..ртуальный", "correct": "вИртуальный" },
    { "withGaps": "в..ртуоз", "correct": "вИртуоз" },
    { "withGaps": "в..траж", "correct": "вИтраж" },
    { "withGaps": "вл..делец", "correct": "влАделец" },
    { "withGaps": "возр..жать", "correct": "возрАжать" },
    { "withGaps": "в..кзал", "correct": "вОкзал" },
    { "withGaps": "в..лейбол", "correct": "вОлейбол" },
    { "withGaps": "вообр..жать", "correct": "вообрАжать" },
    { "withGaps": "вопл..щать", "correct": "воплОщать" },
    { "withGaps": "вп..чатлить", "correct": "впЕчатлить" },
    { "withGaps": "выр..зительный", "correct": "вырАзительный" },
    { "withGaps": "г..зон", "correct": "гАзон" },
    { "withGaps": "г..л..ктический", "correct": "гАлАктический" },
    { "withGaps": "г..л..рея", "correct": "гАлЕрея" },
    { "withGaps": "г..рмония", "correct": "гАрмония" },
    { "withGaps": "г..рн..зон", "correct": "гАрнИзон" },
    { "withGaps": "г..олог", "correct": "гЕолог" },
    { "withGaps": "г..рой", "correct": "гЕрой" },
    { "withGaps": "г..пот..за", "correct": "гИпотЕза" },
    { "withGaps": "г..рмон", "correct": "гОрмон" },
    { "withGaps": "г..рячий", "correct": "гОрячий" },
    { "withGaps": "г..р..зонт", "correct": "гОрИзонт" },
    { "withGaps": "гр..мматика", "correct": "грАмматика" },
    { "withGaps": "грам..та", "correct": "грамОта" },
    { "withGaps": "гр..мадный", "correct": "грОмадный" },
    { "withGaps": "гр..моздкий", "correct": "грОмоздкий" },
    { "withGaps": "д..баты", "correct": "дЕбаты" },
    { "withGaps": "д..корация", "correct": "дЕкорация" },
    { "withGaps": "д..л..к..тес", "correct": "дЕлИкАтес" },
    { "withGaps": "д..л..катный", "correct": "дЕлИкатный" },
    { "withGaps": "д..м..крат", "correct": "дЕмОкрат" },
    { "withGaps": "д..м..нстрировать", "correct": "дЕмОнстрировать" },
    { "withGaps": "д..алог", "correct": "дИалог" },
    { "withGaps": "д..ап..зон", "correct": "дИапАзон" },
    { "withGaps": "д..н..мичный", "correct": "дИнАмичный" },
    { "withGaps": "д..р..жёр", "correct": "дИрИжёр" },
    { "withGaps": "д..сп..тчер", "correct": "дИспЕтчер" },
    { "withGaps": "д..станция", "correct": "дИстанция" },
    { "withGaps": "д..сц..плина", "correct": "дИсцИплина" },
    { "withGaps": "ж..лание", "correct": "жЕлание" },
    { "withGaps": "ж..раф", "correct": "жИраф" },
    { "withGaps": "ж..кей", "correct": "жОкей" },
    { "withGaps": "ж..нглёр", "correct": "жОнглёр" },
    { "withGaps": "ж..ри", "correct": "жЮри" },
    { "withGaps": "зн..комить", "correct": "знАкомить" },
    { "withGaps": "зн..м..нитый", "correct": "знАмЕнитый" },
    { "withGaps": "зн..меновать", "correct": "знАменовать" },
    { "withGaps": "игн..рировать", "correct": "игнОрировать" },
    { "withGaps": "ид..ал", "correct": "идЕал" },
    { "withGaps": "ижд..венец", "correct": "иждИвенец" },
    { "withGaps": "иллюз....нист", "correct": "иллюзИОнист" },
    { "withGaps": "инд..вид", "correct": "индИвид" },
    { "withGaps": "ин..й", "correct": "инЕй" },
    { "withGaps": "инж..нер", "correct": "инжЕнер" },
    { "withGaps": "ин..ц..атива", "correct": "инИцИатива" },
    { "withGaps": "инт..ллект", "correct": "интЕллект" },
    { "withGaps": "инт..ллигент", "correct": "интЕллигент" },
    { "withGaps": "инт..нсивный", "correct": "интЕнсивный" },
    { "withGaps": "инт..рьер", "correct": "интЕрьер" },
    { "withGaps": "иск..зить", "correct": "искАзить" },
    { "withGaps": "ист..на", "correct": "истИна" },
    { "withGaps": "к..мпания (мероприятие)", "correct": "кАмпания (мероприятие)" },
    { "withGaps": "к..никулы", "correct": "кАникулы" },
    { "withGaps": "к..н..тель", "correct": "кАнИтель" },
    { "withGaps": "к..н..нада", "correct": "кАнОнада" },
    { "withGaps": "к..нц..лярия", "correct": "кАнцЕлярия" },
    { "withGaps": "к..пюш..н", "correct": "кАпюшОн" },
    { "withGaps": "к..рд..нальный", "correct": "кАрдИнальный" },
    { "withGaps": "к..р..к..тура", "correct": "кАрИкАтура" },
    { "withGaps": "к..сатка (птица семейства ласточек)", "correct": "кАсатка (птица семейства ласточек)" },
    { "withGaps": "к..т..комба", "correct": "кАтАкомба" },
    { "withGaps": "к..т..строфа", "correct": "кАтАстрофа" },
    { "withGaps": "кв..л..ф..кация", "correct": "квАлИфИкация" },
    { "withGaps": "кв..танция", "correct": "квИтанция" },
    { "withGaps": "аттр..кцион",  "correct":  "аттрАкцион" },
    { "withGaps": "к..н..м..тограф", "correct": "кИнЕмАтограф" },
    { "withGaps": "к..варный", "correct": "кОварный" },
    { "withGaps": "к..лдун", "correct": "кОлдун" },
    { "withGaps": "к..лд..вать", "correct": "кОлдОвать" },
    { "withGaps": "к..л..бание", "correct": "кОлЕбание" },
    { "withGaps": "к..лл..ктив", "correct": "кОллЕктив" },
    { "withGaps": "к..ллекция", "correct": "кОллекция" },
    { "withGaps": "к..л..ссальный", "correct": "кОлОссальный" },
    { "withGaps": "к..лыхать", "correct": "кОлыхать" },
    { "withGaps": "к..мб..нация", "correct": "кОмбИнация" },
    { "withGaps": "к..медия", "correct": "кОмедия" },
    { "withGaps": "к..мпания (группа людей, фирма)", "correct": "кОмпания (группа людей, фирма)" },
    { "withGaps": "к..мп..тентный", "correct": "кОмпЕтентный" },
    { "withGaps": "к..мп..нент", "correct": "кОмпОнент" },
    { "withGaps": "к..мпьютер", "correct": "кОмпьютер" },
    { "withGaps": "к..мфорт", "correct": "кОмфорт" },
    { "withGaps": "к..нверт", "correct": "кОнверт" },
    { "withGaps": "к..нкурент", "correct": "кОнкурент" },
    { "withGaps": "к..нт..нент", "correct": "кОнтИнент" },
    { "withGaps": "к..нф..ренция", "correct": "кОнфЕренция" },
    { "withGaps": "к..нфликт", "correct": "кОнфликт" },
    { "withGaps": "к..нфорка", "correct": "кОнфорка" },
    { "withGaps": "к..р..фей", "correct": "кОрИфей" },
    { "withGaps": "к..ричневый", "correct": "кОричневый" },
    { "withGaps": "к..рзина", "correct": "кОрзина" },
    { "withGaps": "к..роль", "correct": "кОроль" },
    { "withGaps": "к..сатка (млекопитающее семейства дельфиновых)", "correct": "кОсатка (млекопитающее семейства дельфиновых)" },
    { "withGaps": "к..смос", "correct": "кОсмос" },
    { "withGaps": "кр..мешный", "correct": "крОмешный" },
    { "withGaps": "л..б..ринт", "correct": "лАбИринт" },
    { "withGaps": "л..дья", "correct": "лАдья" },
    { "withGaps": "л..генда", "correct": "лЕгенда" },    { "withGaps": "л..леять", "correct": "лЕлеять" },
    { "withGaps": "л..б..рал", "correct": "лИбЕрал" },
    { "withGaps": "л..нгвистика", "correct": "лИнгвистика" },
    { "withGaps": "м..жор", "correct": "мАжор" },
    { "withGaps": "м..жорный", "correct": "мАжорный" },
    { "withGaps": "м..териал", "correct": "мАтериал" },
    { "withGaps": "мгн..вение", "correct": "мгнОвение" },
    { "withGaps": "м..нт..литет", "correct": "мЕнтАлитет" },
    { "withGaps": "м..р..диан", "correct": "мЕрИдиан" },
    { "withGaps": "м..р..приятие", "correct": "мЕрОприятие" },
    { "withGaps": "м..тафора", "correct": "мЕтафора" },
    { "withGaps": "м..ханизм", "correct": "мЕханизм" },
    { "withGaps": "м..н..рал", "correct": "мИнЕрал" },
    { "withGaps": "м..нор", "correct": "мИнор" },
    { "withGaps": "м..н..лит", "correct": "мОнОлит" },
    { "withGaps": "м..р..торий", "correct": "мОрАторий" },
    { "withGaps": "м..тив", "correct": "мОтив" },
    { "withGaps": "м..теж", "correct": "мЯтеж" },
    { "withGaps": "нав..ждение", "correct": "навАждение" },
    { "withGaps": "н..с..комые", "correct": "нАсЕкомые" },
    { "withGaps": "насл..ждаться", "correct": "наслАждаться" },
    { "withGaps": "недос..гаемый", "correct": "недосЯгаемый" },
    { "withGaps": "н..велла", "correct": "нОвелла" },
    { "withGaps": "об..яние", "correct": "обАяние" },
    { "withGaps": "об..ятельный", "correct": "обАятельный" },
    { "withGaps": "об..тать", "correct": "обИтать" },
    { "withGaps": "обн..ружить", "correct": "обнАружить" },
    { "withGaps": "об..няние", "correct": "обОняние" },
    { "withGaps": "об..нятельный", "correct": "обОнятельный" },
    { "withGaps": "об..рона", "correct": "обОрона" },
    { "withGaps": "од..леть", "correct": "одОлеть" },
    { "withGaps": "оз..рной", "correct": "озОрной" },
    { "withGaps": "оп..кун", "correct": "опЕкун" },
    { "withGaps": "опт..мист", "correct": "оптИмист" },
    { "withGaps": "ор..нж..рея", "correct": "орАнжЕрея" },
    { "withGaps": "..рбита", "correct": "Орбита" },
    { "withGaps": "орг..н..зовать", "correct": "оргАнИзовать" },
    { "withGaps": "ор..г..нальный", "correct": "орИгИнальный" },
    { "withGaps": "ор....нтировать", "correct": "орИЕнтировать" },
    { "withGaps": "..рнамент", "correct": "Орнамент" },
    { "withGaps": "оф..цер", "correct": "офИцер" },
    { "withGaps": "ош..л..мить", "correct": "ошЕлОмить" },
    { "withGaps": "п..л..садник", "correct": "пАлИсадник" },
    { "withGaps": "п..литра", "correct": "пАлитра" },
    { "withGaps": "п..н..рама", "correct": "пАнОрама" },
    { "withGaps": "панц..рь", "correct": "панцИрь" },
    { "withGaps": "п..р..граф", "correct": "пАрАграф" },
    { "withGaps": "п..р..докс", "correct": "пАрАдокс" },
    { "withGaps": "п..р..ш..т", "correct": "пАрАшЮт" },
    { "withGaps": "п..триот", "correct": "пАтриот" },
    { "withGaps": "п..йзаж", "correct": "пЕйзаж" },
    { "withGaps": "п..рила", "correct": "пЕрила" },
    { "withGaps": "п..ри..д", "correct": "пЕриОд" },
    { "withGaps": "п..сс..мист", "correct": "пЕссИмист" },
    { "withGaps": "подл..нный", "correct": "подлИнный" },
    { "withGaps": "подр..жать", "correct": "подрАжать" },
    { "withGaps": "п..зиция", "correct": "пОзиция" },
    { "withGaps": "п..кой", "correct": "пОкой" },
    { "withGaps": "пок..ление", "correct": "покОление" },
    { "withGaps": "п..лемика", "correct": "пОлемика" },
    { "withGaps": "п..л..ровать", "correct": "пОлИровать" },
    { "withGaps": "пор..жать", "correct": "порАжать" },
    { "withGaps": "пор..зить", "correct": "порАзить" },
    { "withGaps": "пос..щать", "correct": "посЕщать" },
    { "withGaps": "прав..ло", "correct": "правИло" },
    { "withGaps": "предв..рительный", "correct": "предвАрительный" },
    { "withGaps": "пр..з..нтация", "correct": "прЕзЕнтация" },
    { "withGaps": "пр..з..дент", "correct": "прЕзИдент" },
    { "withGaps": "пр..зидиум", "correct": "прЕзидиум" },
    { "withGaps": "пр..обр..зить", "correct": "прЕобрАзить" },
    { "withGaps": "пр..од..леть", "correct": "прЕодОлеть" },
    { "withGaps": "пр..ц..дент", "correct": "прЕцЕдент" },
    { "withGaps": "пр..в..легия", "correct": "прИвИлегия" },
    { "withGaps": "пр..м..тивный", "correct": "прИмИтивный" },
    { "withGaps": "пр..ор..тет", "correct": "прИорИтет" },
    { "withGaps": "пр..винция",  "correct":  "прОвинция"  },
    {  "withGaps":  "пр..в..цировать",  "correct":  "прОвОцировать"  },
    {  "withGaps":  "пр..н..цательный",  "correct":  "прОнИцательный"  },
    { "withGaps": "пр..н..цательный", "correct": "прОнИцательный" },
    { "withGaps": "р..д..атор", "correct": "рАдИатор" },
    { "withGaps": "рац..ональный", "correct": "рацИональный" },
    { "withGaps": "р....лист", "correct": "рЕАлист" },
    { "withGaps": "р..ж..ссёр", "correct": "рЕжИссёр" },
    { "withGaps": "р..з..дент", "correct": "рЕзИдент" },
    { "withGaps": "р..з..денция", "correct": "рЕзИденция" },
    { "withGaps": "р..м..сло", "correct": "рЕмЕсло" },
    { "withGaps": "р..ст..врация", "correct": "рЕстАврация" },
    { "withGaps": "р..ф..рат", "correct": "рЕфЕрат" },
    { "withGaps": "р..форма", "correct": "рЕформа" },
    { "withGaps": "р..цензия", "correct": "рЕцензия" },
    { "withGaps": "р..торика", "correct": "рИторика" },
    { "withGaps": "р..весники", "correct": "рОвесники" },
    { "withGaps": "р..мантичный", "correct": "рОмантичный" },
    { "withGaps": "с..лют", "correct": "сАлют" },
    { "withGaps": "с..тира", "correct": "сАтира" },
    { "withGaps": "св..рливый", "correct": "свАрливый" },
    { "withGaps": "св..детель", "correct": "свИдетель" },
    { "withGaps": "с..зон", "correct": "сЕзон" },
    { "withGaps": "с..мпатия", "correct": "сИмпатия" },
    { "withGaps": "с..мптом", "correct": "сИмптом" },
    { "withGaps": "с..мфония", "correct": "сИмфония" },
    { "withGaps": "с..нхронный", "correct": "сИнхронный" },
    { "withGaps": "с..рень", "correct": "сИрень" },
    { "withGaps": "с..стема", "correct": "сИстема" },
    { "withGaps": "см..тение", "correct": "смЯтение" },
    { "withGaps": "сн..р..дить", "correct": "снАрЯдить" },
    { "withGaps": "сокр..венный", "correct": "сокрОвенный" },
    { "withGaps": "с..нет", "correct": "сОнет" },
    { "withGaps": "состр..дать", "correct": "сострАдать" },
    { "withGaps": "сост..заться", "correct": "состЯзаться" },
    { "withGaps": "с..ц..альный",  "correct":  "cОцИальный"  },
    {  "withGaps":  "сп..ртакиада",  "correct":  "спАртакиада"  },
    {  "withGaps":  "сп..койный",  "correct":  "спОкойный"  },
    {  "withGaps":  "ст..д..он",  "correct":  "стАдИон"  },
    {  "withGaps":  "ст..пендия",  "correct":  "стИпендия"  },
    {  "withGaps":  "стр..ховать",  "correct":  "стрАховать"  },
    {  "withGaps":  "стр..миться",  "correct":  "стрЕмиться"  },
    {  "withGaps":  "cув..рен..тет",  "correct":  "cувЕренИтет"  },
    {  "withGaps":  "cув..нир",  "correct":  "cувЕнир" },
    { "withGaps": "сум..рки", "correct": "сумЕрки" },
    { "withGaps": "т..лант", "correct": "тАлант" },
    { "withGaps": "т..ория", "correct": "тЕория" },
    { "withGaps": "т..рр..тория", "correct": "тЕррИтория" },
    { "withGaps": "т..ржество", "correct": "тОржество" },
    { "withGaps": "тр..диция", "correct": "трАдиция" },
    { "withGaps": "тр..ф..рет", "correct": "трАфАрет" },
    { "withGaps": "тр..вога", "correct": "трЕвога" },
    { "withGaps": "тр..мвай", "correct": "трАмвай" },
    { "withGaps": "тр..ллейбус", "correct": "трОллейбус" },
    { "withGaps": "тр..стник", "correct": "трОстник" },
    { "withGaps": "тр..туар", "correct": "трОтуар" },
    { "withGaps": "тр..сина", "correct": "трЯсина" },
    { "withGaps": "уг..стить", "correct": "угОстить" },
    { "withGaps": "ун..в..рситет", "correct": "унИвЕрситет" },
    { "withGaps": "ун..кальный", "correct": "унИкальный" },
    { "withGaps": "ун..чтожить", "correct": "унИчтожить" },
    { "withGaps": "утр..мбовать", "correct": "утрАмбовать" },
    { "withGaps": "у..звить", "correct": "уЯзвить" },
    { "withGaps": "ф..нтастика", "correct": "фАнтастика" },
    { "withGaps": "ф..ст..валь", "correct": "фЕстИваль" },
    { "withGaps": "ф..гура", "correct": "фИгура" },
    { "withGaps": "ф..нансы", "correct": "фИнансы" },
    { "withGaps": "ф....летовый", "correct": "фИОлетовый" },
    { "withGaps": "фр..гмент", "correct": "фрАгмент" },
    { "withGaps": "фраз..ология", "correct": "фразЕология" },
    { "withGaps": "ха..с", "correct": "хаОс" },
    { "withGaps": "х..рактер", "correct": "хАрактер" },
    { "withGaps": "ц..мент", "correct": "цЕмент" },
    { "withGaps": "ц..в..л..зация", "correct": "цИвИлИзация" },
    { "withGaps": "ц..клон", "correct": "цИклон" },
    { "withGaps": "ц..линдр", "correct": "цИлиндр" },
    { "withGaps": "ц..стерна", "correct": "цИстерна" },
    { "withGaps": "ц..тата", "correct": "цИтата" },
    { "withGaps": "ц..ган", "correct": "цЫган" },
    { "withGaps": "ц..плёнок",  "correct":  "цЫплёнок"  },
    {  "withGaps":  "ц..почки",  "correct":  "цЫпочки"  },
    {  "withGaps":  "ч..л..век",  "correct":  "чЕлОвек"  },
    {  "withGaps":  "ч..мп..он",  "correct":  "чЕмпИон"  },
    {  "withGaps":  "ш..ренга",  "correct":  "шЕренга"  },
    {  "withGaps":  "ш..к..лад",  "correct":  "шОкОлад"  },
    {  "withGaps":  "ш..ссе",  "correct":  "шОссе"  },
    {  "withGaps":  "ш..фёр",  "correct":  "шОфёр"  },
    {  "withGaps":  "эв..люция",  "correct":  "эвОлюция"  },
    {  "withGaps":  "эк..н..мический",  "correct":  "экОнОмический"  },
    {  "withGaps":  "эксп..р..мент",  "correct":  "экспЕрИмент"  },
    {  "withGaps":  "эксп..нат",  "correct":  "экспОнат"  },
    {  "withGaps":  "экстр..мальный",  "correct":  "экстрЕмальный"  },
    {  "withGaps":  "эл..ктроника",  "correct":  "элЕктроника"  },
    {  "withGaps":  "энц..кл..педия",  "correct":  "энцИклОпедия"  },
    {  "withGaps":  "эст..када",  "correct":  "эстАкада"}
]
    


  return (
    <div className="container mx-auto px-4 py-8 md:py-12 flex flex-col items-center">
      <div className="w-full max-w-md mb-6">
        <Link
          href="/"
          className="inline-flex items-center text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Вернуться на главную
        </Link>
      </div>

      <WordLearningTest
        words={words}
        title="Учим правописание слов"
        description="Заполните пропущенные буквы в словах"
      />
    </div>
  )
}

